services:
  - type: web
    name: proyecto-personal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ProyectoWeb.wsgi:application"
    postDeployCommand: >
      python manage.py migrate &&
      python manage.py loaddata datos.json &&
      python manage.py collectstatic --noinput
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ProyectoDjangoDB
          property: connectionString

      - key: SECRET_KEY
        value: django-insecure-v18d5lwz6b6urfr8*a881=t0t*k2oc8h=g71pbgi&exo1(zj#c

      - key: DEBUG
        value: "False"

      - key: EMAIL_HOST_USER
        value: xbrand9000@gmail.com

      - key: EMAIL_HOST_PASSWORD
        value: febevecmjwrgoyxw

      - key: PAYPAL_CLIENT_ID
        value: Af7vBYFRhw7wZ7Nt-Ap8SHezlj9Nx5frzmNWVK8k0DT8gu9eMb_EhSwGcuvj6MwhUok1kR-ukjk8i3xh

      - key: PAYPAL_SECRET
        value: EMZuPLbOe0Xmf4gGCa0k9WIpomNNZPN3siLqmPcKttf7QLJixLCr6MpOcAXoHWOdJcsMDdwfTrn0aqB9

      - key: PAYPAL_RECEIVER_EMAIL
        value: sb-x28pe30375611@business.example.com