# Generated by Django 5.0.7 on 2025-06-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_pedido_user_delete_lineapedido_delete_pedido'),
        ('tienda', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='CategoriaProd',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
