# Generated by Django 5.0.7 on 2025-06-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_remove_pedido_user_delete_lineapedido_delete_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_paqueteria', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('pedido', models.CharField(max_length=255)),
                ('pedido_confirmado', models.BooleanField(default=False)),
                ('proceso_recoleccion', models.BooleanField(default=False)),
                ('proceso_envio', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paqueteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_paqueteria', models.CharField(max_length=255, unique=True)),
                ('contraseña_paqueteria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.FloatField()),
            ],
        ),
    ]
