# Generated by Django 5.0.7 on 2025-06-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_usuario_pedido_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
    ]
