# Generated by Django 5.0.7 on 2025-06-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
