# Generated by Django 5.0.7 on 2025-06-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('pedido', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
